POST http://localhost:8080/medicalSpecialty
Content-Type: application/json

{

  "name": "teste 1",
  "description": "lupus"

}

###

GET http://localhost:8080/medicalSpecialty
Content-Type: application/json


###
GET http://localhost:8080/notes/662cf55982682b0101adf3cc
Content-Type: application/json



###
DELETE http://localhost:8080/notes/662cf55982682b0101adf3cc
Content-Type: application/json